
import { LawEnforcementAgency, LawEnforcementReport } from '@shared/schema';
import { storage } from './storage';
import { forensicsAnalyzer } from './forensicsAnalyzer';

export class LawEnforcementIntegration {
  async submitReport(reportId: number, agencyId: number): Promise<LawEnforcementReport> {
    const report = await storage.getReport(reportId);
    const agency = await storage.getLawEnforcementAgency(agencyId);
    
    if (!report || !agency) {
      throw new Error('Report or agency not found');
    }

    // Generate tracking number
    const trackingNumber = `LEA-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    // Create law enforcement report
    const lawEnforcementReport = await storage.createLawEnforcementReport({
      userId: report.userId,
      agencyId: agency.id,
      reportId: report.id,
      trackingNumber,
      status: 'pending',
      priority: this.determinePriority(report),
      incidentDate: report.timestamp,
      incidentLocation: report.location,
      evidenceIncluded: ['audio_recording', 'spectrum_analysis', 'location_data'],
      reportContent: {
        summary: `Sonic attack detected at ${report.location}`,
        details: `Attack detected using frequencies: ${JSON.stringify(report.frequencyData)}`,
        victimStatement: 'Automatically generated by SENTINEL system',
        technicalAnalysis: report.mlClassification,
        mediaFiles: []
      }
    });

    // Notify agency through their API if available
    if (agency.apiKey) {
      await this.notifyAgency(agency, lawEnforcementReport);
    }

    return lawEnforcementReport;
  }

  private determinePriority(report: any): string {
    const intensity = report.frequencyData?.magnitude || 0;
    if (intensity > 90) return 'critical';
    if (intensity > 70) return 'high';
    if (intensity > 50) return 'medium';
    return 'low';
  }

  private async notifyAgency(agency: LawEnforcementAgency, report: LawEnforcementReport) {
    // Implementation would vary based on agency's API
    console.log(`Notifying agency ${agency.name} about report ${report.trackingNumber}`);
  }
}

export const lawEnforcementIntegration = new LawEnforcementIntegration();
